"""add classroom colum to subjects

Revision ID: 3bc8a142185a
Revises: e296e8d0246d
Create Date: 2026-06-03 21:08:33.770459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc8a142185a'
down_revision: Union[str, Sequence[str], None] = 'e296e8d0246d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('classroom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'classroom')
    # ### end Alembic commands ###
