"""add deadlines table

Revision ID: 8289812499fc
Revises: 3bc8a142185a
Create Date: 2026-06-04 07:45:16.781954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8289812499fc'
down_revision: Union[str, Sequence[str], None] = '3bc8a142185a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('title', sa.String(), nullable=True))
    op.add_column('deadlines', sa.Column('type', sa.String(), nullable=True))
    op.add_column('deadlines', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('deadlines', sa.Column('classroom', sa.String(), nullable=True))
    op.add_column('deadlines', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deadlines', 'plans', ['plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deadlines', type_='foreignkey')
    op.drop_column('deadlines', 'plan_id')
    op.drop_column('deadlines', 'classroom')
    op.drop_column('deadlines', 'due_date')
    op.drop_column('deadlines', 'type')
    op.drop_column('deadlines', 'title')
    # ### end Alembic commands ###
