"""perf: add database indexes to users plans and subjects tables

Revision ID: 43f291648ed0
Revises: 0a88706daca3
Create Date: 2026-06-12 13:08:45.247096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f291648ed0'
down_revision: Union[str, Sequence[str], None] = '0a88706daca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_plans_owner_id'), 'plans', ['owner_id'], unique=False)
    op.create_index(op.f('ix_subjects_plan_id'), 'subjects', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_plan_id'), table_name='subjects')
    op.drop_index(op.f('ix_plans_owner_id'), table_name='plans')
    # ### end Alembic commands ###
