"""add_plan_fields

Revision ID: a26a3dbe0db6
Revises: 43f291648ed0
Create Date: 2026-06-28 07:59:08.652708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26a3dbe0db6'
down_revision: Union[str, Sequence[str], None] = '43f291648ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('semester', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('plans', sa.Column('accent_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'accent_color')
    op.drop_column('plans', 'start_date')
    op.drop_column('plans', 'semester')
    # ### end Alembic commands ###
